version: "3.8"
services:
  api:
    env_file: ./.env
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    ports:
      - "4040:4040"
    volumes:
      - ./database:/app/database
    command: ["npm", "start"]
