version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: 'always'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'